version: 2

build:
  os: ubuntu-22.04
  commands:
    - curl -fsSL https://pixi.sh/install.sh | sh
    - source $HOME/.bashrc
    - pixi run build-docs
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - rm -rf $READTHEDOCS_OUTPUT/html && mv docs/_build/html $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt